# Generated by Django 5.1.3 on 2025-04-09 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CivilBuildingWear', '0001_initial'),
        ('buildings', '0010_alter_house_meter_state_alter_house_roof_shape'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='civilbuilding',
            options={'verbose_name': 'Расчетная информация о здании', 'verbose_name_plural': 'Расчетная информация о зданиях'},
        ),
        migrations.AlterModelOptions(
            name='civilbuildingdamage',
            options={'verbose_name': 'Износ здания', 'verbose_name_plural': 'Износ зданий'},
        ),
        migrations.AlterModelOptions(
            name='doors',
            options={'verbose_name': 'Дверь', 'verbose_name_plural': 'Двери'},
        ),
        migrations.AlterModelOptions(
            name='window',
            options={'verbose_name': 'Окно', 'verbose_name_plural': 'Окна'},
        ),
        migrations.AlterField(
            model_name='civilbuilding',
            name='originalHouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.house', verbose_name='id оригинального здания'),
        ),
    ]
