# Generated by Django 5.1.3 on 2024-12-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_rename_house_id_lift_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='attic_insulation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Утепляющие слои чердачных перекрытий'),
        ),
        migrations.AlterField(
            model_name='house',
            name='balconies_wear',
            field=models.FloatField(blank=True, null=True, verbose_name='Физический износ, %'),
        ),
        migrations.AlterField(
            model_name='house',
            name='balcony_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество балконов'),
        ),
        migrations.AlterField(
            model_name='house',
            name='cadastre_number',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Кадастровый номер (инвентарный или условный номер)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='cold_water_inlets_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество вводов внутридомовой инженерной системы холодного водоснабжения в здание (количество точек поставки)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='cold_water_last_repair_year',
            field=models.DateField(blank=True, null=True, verbose_name='Год проведения последнего капитального ремонта'),
        ),
        migrations.AlterField(
            model_name='house',
            name='cold_water_network_material',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Материал сети'),
        ),
        migrations.AlterField(
            model_name='house',
            name='cold_water_network_wear',
            field=models.FloatField(blank=True, null=True, verbose_name='Физический износ, %'),
        ),
        migrations.AlterField(
            model_name='house',
            name='cold_water_system_type',
            field=models.IntegerField(blank=True, choices=[(1, 'хозяйственно-питьевая'), (2, 'противопожарная/производственная'), (3, 'совмещенная')], null=True, verbose_name='Тип внутридомовой инженерной системы холодного водоснабжения'),
        ),
        migrations.AlterField(
            model_name='house',
            name='cold_water_wear',
            field=models.FloatField(blank=True, null=True, verbose_name='Физический износ, %'),
        ),
        migrations.AlterField(
            model_name='house',
            name='commissioning_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата ввода в эксплуатацию'),
        ),
        migrations.AlterField(
            model_name='house',
            name='common_area_wear',
            field=models.FloatField(blank=True, null=True, verbose_name='Физический износ, %'),
        ),
        migrations.AlterField(
            model_name='house',
            name='date_of_passport_generation',
            field=models.DateField(auto_now_add=True, verbose_name='Дата формирования электронного паспорта '),
        ),
        migrations.AlterField(
            model_name='house',
            name='doors_wear',
            field=models.FloatField(blank=True, null=True, verbose_name='Физический износ, %'),
        ),
        migrations.AlterField(
            model_name='house',
            name='electricity_inlets_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество вводов внутридомовой инженерной системы электроснабжения в здание(количество точек поставки)  '),
        ),
        migrations.AlterField(
            model_name='house',
            name='electricity_last_repair_year',
            field=models.DateField(blank=True, null=True, verbose_name='Год проведения последнего капитального ремонта'),
        ),
        migrations.AlterField(
            model_name='house',
            name='electricity_wear',
            field=models.FloatField(blank=True, null=True, verbose_name='Физический износ, %'),
        ),
        migrations.AlterField(
            model_name='house',
            name='element_last_repair_year',
            field=models.DateField(blank=True, null=True, verbose_name='Год проведения последнего капитального ремонта'),
        ),
        migrations.AlterField(
            model_name='house',
            name='element_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Наименование конструктивного элемента'),
        ),
        migrations.AlterField(
            model_name='house',
            name='element_wear',
            field=models.FloatField(blank=True, null=True, verbose_name='Физический износ, %'),
        ),
        migrations.AlterField(
            model_name='house',
            name='external_walls_material',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Материал наружных стен'),
        ),
        migrations.AlterField(
            model_name='house',
            name='external_walls_type',
            field=models.IntegerField(blank=True, choices=[(1, 'несущие'), (2, 'самонесущие'), (3, 'ненесущие/фахверковые'), (4, 'навесные')], null=True, verbose_name='Тип наружных стен'),
        ),
        migrations.AlterField(
            model_name='house',
            name='external_walls_wear',
            field=models.FloatField(blank=True, null=True, verbose_name='Физический износ, наружных стен, %'),
        ),
        migrations.AlterField(
            model_name='house',
            name='facade_cladding_material',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тип наружного утепления фасада'),
        ),
        migrations.AlterField(
            model_name='house',
            name='facade_insulation_type',
            field=models.IntegerField(blank=True, choices=[(1, 'навесные вентилируемые'), (2, 'слоистой (колодцевой) кладки'), (3, 'штукатурные')], null=True, verbose_name='Тип наружного утепления фасада'),
        ),
        migrations.AlterField(
            model_name='house',
            name='facade_last_repair_year',
            field=models.DateField(blank=True, null=True, verbose_name='Год проведения последнего капитального ремонта'),
        ),
        migrations.AlterField(
            model_name='house',
            name='floorCount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество этажей'),
        ),
        migrations.AlterField(
            model_name='house',
            name='floor_structure',
            field=models.IntegerField(blank=True, choices=[(1, 'сборная'), (2, 'монолитная'), (3, 'сборно-монолитная'), (4, 'из дервянных балок'), (5, 'из металлических балок'), (6, 'железобетонные')], null=True, verbose_name='Конструкция перекрытий '),
        ),
        migrations.AlterField(
            model_name='house',
            name='floor_type',
            field=models.IntegerField(blank=True, choices=[(1, 'балочные'), (2, 'плитные'), (3, 'безбалочные')], null=True, verbose_name='Тип перекрытий'),
        ),
        migrations.AlterField(
            model_name='house',
            name='floor_wear',
            field=models.FloatField(blank=True, null=True, verbose_name='Физический износ, %'),
        ),
        migrations.AlterField(
            model_name='house',
            name='foundation_last_repair_year',
            field=models.DateField(blank=True, null=True, verbose_name='Год проведения последнего капитального ремонта '),
        ),
        migrations.AlterField(
            model_name='house',
            name='foundation_material',
            field=models.IntegerField(blank=True, choices=[(1, 'бутовый'), (2, 'бетонный'), (3, 'бутобетонный'), (4, 'железобетонный')], null=True, verbose_name='Материал фундамента'),
        ),
        migrations.AlterField(
            model_name='house',
            name='foundation_type',
            field=models.IntegerField(blank=True, choices=[(1, 'монолитный'), (2, 'плавающий'), (3, 'ленточный'), (4, 'плитный'), (5, 'свайный'), (6, 'винтовые сваи'), (7, 'столбчатый')], null=True, verbose_name='Тип фундамента'),
        ),
        migrations.AlterField(
            model_name='house',
            name='foundation_wear',
            field=models.FloatField(blank=True, null=True, verbose_name='Физический износ, %'),
        ),
        migrations.AlterField(
            model_name='house',
            name='gas_inlets_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество вводов внутридомовой инженерной системы газоснабжения в здание (количество точек поставки)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='gas_last_repair_year',
            field=models.DateField(blank=True, null=True, verbose_name='Год проведения последнего капитального ремонта'),
        ),
        migrations.AlterField(
            model_name='house',
            name='gas_system_type',
            field=models.IntegerField(blank=True, choices=[(1, 'централизованная'), (2, 'автономная')], null=True, verbose_name='Тип внутридомовой инженерной системы газоснабжения'),
        ),
        migrations.AlterField(
            model_name='house',
            name='heat_source_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тип теплоисточника или теплоносителя внутридомовой системы отопления'),
        ),
        migrations.AlterField(
            model_name='house',
            name='heating_inlets_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество вводов системы отопления в здание (количество точек поставки)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='heating_last_repair_year',
            field=models.DateField(blank=True, null=True, verbose_name='Год проведения последнего капитального ремонта'),
        ),
        migrations.AlterField(
            model_name='house',
            name='heating_system_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тип внутридомовой системы отопления'),
        ),
        migrations.AlterField(
            model_name='house',
            name='heating_wear',
            field=models.FloatField(blank=True, null=True, verbose_name='Физический износ, %'),
        ),
        migrations.AlterField(
            model_name='house',
            name='hot_water_inlets_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество вводов внутридомовой инженерной системы горячего водоснабжения в здание (количество точек поставки)  '),
        ),
        migrations.AlterField(
            model_name='house',
            name='hot_water_last_repair_year',
            field=models.DateField(blank=True, null=True, verbose_name='Год проведения последнего капитального ремонта'),
        ),
        migrations.AlterField(
            model_name='house',
            name='hot_water_network_wear',
            field=models.FloatField(blank=True, null=True, verbose_name='Физический износ, %'),
        ),
        migrations.AlterField(
            model_name='house',
            name='hot_water_system_type',
            field=models.IntegerField(blank=True, choices=[(1, 'открытая'), (2, 'закрытая')], null=True, verbose_name='Тип внутридомовой инженерной системы горячего водоснабжения '),
        ),
        migrations.AlterField(
            model_name='house',
            name='hot_water_wear',
            field=models.FloatField(blank=True, null=True, verbose_name='Физический износ, %'),
        ),
        migrations.AlterField(
            model_name='house',
            name='internal_walls_material',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Материал внутренних стен'),
        ),
        migrations.AlterField(
            model_name='house',
            name='internal_walls_type',
            field=models.IntegerField(blank=True, choices=[(1, 'несущие'), (2, 'самонесущие'), (3, 'навесные')], null=True, verbose_name='Тип внутренних стен'),
        ),
        migrations.AlterField(
            model_name='house',
            name='internal_walls_wear',
            field=models.FloatField(blank=True, null=True, verbose_name='Физический износ, %'),
        ),
        migrations.AlterField(
            model_name='house',
            name='life_cycle_stage',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Стадия жизненного цикла'),
        ),
        migrations.AlterField(
            model_name='house',
            name='lodji_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество лоджий'),
        ),
        migrations.AlterField(
            model_name='house',
            name='meter_brand',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Марка прибора учета'),
        ),
        migrations.AlterField(
            model_name='house',
            name='meter_state',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='house',
            name='network_insulation_material',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Материал теплоизоляции сети'),
        ),
        migrations.AlterField(
            model_name='house',
            name='network_material',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Материал сети'),
        ),
        migrations.AlterField(
            model_name='house',
            name='network_wear',
            field=models.FloatField(blank=True, null=True, verbose_name='Физический износ, %'),
        ),
        migrations.AlterField(
            model_name='house',
            name='number_auxiliary_rooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество вспомогательных помещений , в т.ч. общего пользования'),
        ),
        migrations.AlterField(
            model_name='house',
            name='number_elevators',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество лифтов'),
        ),
        migrations.AlterField(
            model_name='house',
            name='number_entrances',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество подъездов'),
        ),
        migrations.AlterField(
            model_name='house',
            name='number_working_rooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество рабочих помещений (кабинетов, аудиторий)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='only_cold_water_network_material',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Материал сети'),
        ),
        migrations.AlterField(
            model_name='house',
            name='only_cold_water_network_wear',
            field=models.FloatField(blank=True, null=True, verbose_name='Физический износ, %'),
        ),
        migrations.AlterField(
            model_name='house',
            name='only_cold_water_risers_material',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Материал теплоизоляции сети'),
        ),
        migrations.AlterField(
            model_name='house',
            name='only_cold_water_risers_wear',
            field=models.FloatField(blank=True, null=True, verbose_name='Физический износ, %'),
        ),
        migrations.AlterField(
            model_name='house',
            name='only_cold_water_valves_wear',
            field=models.FloatField(blank=True, null=True, verbose_name='Физический износ, %'),
        ),
        migrations.AlterField(
            model_name='house',
            name='only_hot_water_network_material',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Материал сети'),
        ),
        migrations.AlterField(
            model_name='house',
            name='only_hot_water_network_network_insulation_material',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Материал теплоизоляции сети'),
        ),
        migrations.AlterField(
            model_name='house',
            name='only_hot_water_risers_material',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Материал теплоизоляции сети'),
        ),
        migrations.AlterField(
            model_name='house',
            name='only_hot_water_risers_wear',
            field=models.FloatField(blank=True, null=True, verbose_name='Физический износ, %'),
        ),
        migrations.AlterField(
            model_name='house',
            name='only_hot_water_valves_wear',
            field=models.FloatField(blank=True, null=True, verbose_name='Физический износ, %'),
        ),
        migrations.AlterField(
            model_name='house',
            name='paving_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь отмостки, КВ.м'),
        ),
        migrations.AlterField(
            model_name='house',
            name='planned_verification_date',
            field=models.DateField(blank=True, null=True, verbose_name='Плановая дата поверки '),
        ),
        migrations.AlterField(
            model_name='house',
            name='purpose_of_building',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Назначение здания'),
        ),
        migrations.AlterField(
            model_name='house',
            name='radiators_type',
            field=models.IntegerField(blank=True, choices=[(1, 'радиаторы'), (2, 'конвекторы'), (3, 'полотенцесушители'), (4, 'стеновые панели'), (4, 'тёплые полы'), (4, 'инфракрасные излучатели')], null=True, verbose_name='Тип отопительных приборов '),
        ),
        migrations.AlterField(
            model_name='house',
            name='radiators_wear',
            field=models.FloatField(blank=True, null=True, verbose_name='Физический износ, %'),
        ),
        migrations.AlterField(
            model_name='house',
            name='resource_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Наименование коммунального ресурса, для измерения объемов поставки которого используется общедомовой прибор учета '),
        ),
        migrations.AlterField(
            model_name='house',
            name='risers_wear',
            field=models.FloatField(blank=True, null=True, verbose_name='Физический износ, %'),
        ),
        migrations.AlterField(
            model_name='house',
            name='roof_cover_last_repair_year',
            field=models.DateField(blank=True, null=True, verbose_name='Год проведения последнего капитального ремонта'),
        ),
        migrations.AlterField(
            model_name='house',
            name='roof_cover_type',
            field=models.IntegerField(blank=True, choices=[(1, 'листовые материалы'), (2, 'мягкие покрытия'), (3, 'штучная отделка'), (4, 'наливная')], null=True, verbose_name='Тип кровли'),
        ),
        migrations.AlterField(
            model_name='house',
            name='roof_cover_wear',
            field=models.FloatField(blank=True, null=True, verbose_name='Физический износ, %'),
        ),
        migrations.AlterField(
            model_name='house',
            name='roof_last_repair_year',
            field=models.DateField(blank=True, null=True, verbose_name='Год проведения последнего капитального ремонта'),
        ),
        migrations.AlterField(
            model_name='house',
            name='roof_shape',
            field=models.IntegerField(blank=True, choices=[(1, 'сборная'), (2, 'монолитная'), (3, 'сборно-монолитная'), (4, 'из дервянных балок'), (5, 'из металлических балок'), (6, 'железобетонные')], null=True, verbose_name='Конструкция перекрытий '),
        ),
        migrations.AlterField(
            model_name='house',
            name='roof_structure_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вид несущей части'),
        ),
        migrations.AlterField(
            model_name='house',
            name='roof_structure_wear',
            field=models.FloatField(blank=True, null=True, verbose_name='Физический износ, %'),
        ),
        migrations.AlterField(
            model_name='house',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заводской номер (серийный)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='stoves_last_repair_year',
            field=models.DateField(blank=True, null=True, verbose_name='Год проведения последнего капитального ремонта'),
        ),
        migrations.AlterField(
            model_name='house',
            name='stoves_wear',
            field=models.FloatField(blank=True, null=True, verbose_name='Физический износ, %'),
        ),
        migrations.AlterField(
            model_name='house',
            name='tariff_zone_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вид прибора учета в зависимости от тарифных зон суток '),
        ),
        migrations.AlterField(
            model_name='house',
            name='total_area_auxiliary_premises_except_common_areas',
            field=models.FloatField(blank=True, null=True, verbose_name='Общая площадь вспомогательных помещений, за исключением помещений общего пользования, кв.м '),
        ),
        migrations.AlterField(
            model_name='house',
            name='total_area_common_areas_building',
            field=models.FloatField(blank=True, null=True, verbose_name='Общая площадь помещений общего пользования в здании, кв.м '),
        ),
        migrations.AlterField(
            model_name='house',
            name='total_area_working_premises',
            field=models.FloatField(blank=True, null=True, verbose_name='Общая площадь рабочих помещений, кв.м'),
        ),
        migrations.AlterField(
            model_name='house',
            name='underground_floor_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество подземных этажей'),
        ),
        migrations.AlterField(
            model_name='house',
            name='unit',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='house',
            name='valves_wear',
            field=models.FloatField(blank=True, null=True, verbose_name='Физический износ, %'),
        ),
        migrations.AlterField(
            model_name='house',
            name='verification_interval',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Межповерочный интервал '),
        ),
        migrations.AlterField(
            model_name='house',
            name='wastewater_last_repair_year',
            field=models.DateField(blank=True, null=True, verbose_name='Год проведения последнего капитального ремонта'),
        ),
        migrations.AlterField(
            model_name='house',
            name='wastewater_system_type',
            field=models.IntegerField(blank=True, choices=[(1, 'централизованная канализация'), (2, 'выгребная яма'), (3, 'локальная канализация (септик)')], null=True, verbose_name='Тип внутридомовой инженерной системы водоотведения '),
        ),
        migrations.AlterField(
            model_name='house',
            name='wastewater_wear',
            field=models.FloatField(blank=True, null=True, verbose_name='Физический износ, %'),
        ),
        migrations.AlterField(
            model_name='house',
            name='windows_material',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Материал окон'),
        ),
        migrations.AlterField(
            model_name='house',
            name='windows_wear',
            field=models.FloatField(blank=True, null=True, verbose_name='Физический износ, %'),
        ),
        migrations.AlterField(
            model_name='house',
            name='year_construction',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год постройки'),
        ),
        migrations.AlterField(
            model_name='house',
            name='year_operation',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год ввода в эксплуатацию'),
        ),
        migrations.AlterField(
            model_name='house',
            name='year_reconstruction',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год проведения реконструкции'),
        ),
    ]
