# Generated by Django 5.1.3 on 2024-12-03 16:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_alter_house_attic_insulation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='manage_org',
            field=models.CharField(default=django.utils.timezone.now, help_text='Обязательное поле', max_length=255, verbose_name='Управляющая организация'),
            preserve_default=False,
        ),
    ]
