# Generated by Django 5.1.3 on 2024-12-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_house_manage_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='wastewater_system_material',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Материал теплоизоляции сети'),
        ),
        migrations.AlterField(
            model_name='house',
            name='resource_name',
            field=models.CharField(blank=True, choices=[('централизованная', 'централизованная'), ('автономная', 'автономная')], max_length=200, null=True, verbose_name='Наименование коммунального ресурса, для измерения объемов поставки которого используется общедомовой прибор учета'),
        ),
    ]
