# Generated by Django 5.1.3 on 2024-12-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0009_alter_house_cold_water_last_repair_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='meter_state',
            field=models.CharField(blank=True, choices=[('в работе', 'в работе'), ('в резерве', 'в резерве'), ('ремонт', 'ремонт')], max_length=200, null=True, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='house',
            name='roof_shape',
            field=models.CharField(blank=True, choices=[('односкатная', 'односкатная'), ('двускатная', 'двускатная'), ('четырехскатная', 'четырехскатная'), ('многоскатная', 'многоскатная'), ('плоская', 'плоская')], max_length=255, null=True, verbose_name='Форма крыши'),
        ),
    ]
