# Generated by Django 5.1.3 on 2025-02-17 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=100, verbose_name='Объект')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Исполнитель')),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Специалист')),
            ],
        ),
        migrations.CreateModel(
            name='Seti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_choices', models.IntegerField(choices=[(1, 'Первичная'), (2, 'Повторная')], default=1, verbose_name='Тип обращения')),
                ('applicant_type', models.IntegerField(choices=[(1, 'Гражданин'), (2, 'Госорганы'), (3, 'Организация')], default=1, verbose_name='Тип заявителя')),
                ('category_choices', models.IntegerField(choices=[(1, 'Аварийная'), (2, 'Плановая'), (3, 'Консультация')], default=1, verbose_name='Категория заявки')),
                ('resource_choices', models.IntegerField(choices=[(1, 'Тепло'), (2, 'Водоснабжение'), (3, 'Канализация'), (4, 'Благоустройство')], default=1, verbose_name='Ресурс')),
                ('avaria_choices', models.IntegerField(choices=[(1, 'Котельная'), (2, 'ЦТП'), (3, 'Камера'), (4, 'Течь сети'), (1, 'Течь сети'), (2, 'Колодец'), (3, 'Течь пожарного гидранта'), (4, 'Колонка'), (1, 'Засор канализации'), (2, 'Течь сети'), (3, 'Течь колодца'), (4, 'Иное'), (1, 'Разрушен колодец'), (2, 'Иное')], verbose_name='Объект аварии')),
                ('status', models.IntegerField(choices=[(1, 'Новая'), (2, 'Передано на исполнение'), (3, 'В работе'), (4, 'Завершена')], default=1, verbose_name='Статус заявки')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО заявителя')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон заявителя')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('description', models.TextField(verbose_name='Примечание')),
                ('due_date_start', models.DateField(verbose_name='Дата начала исполнения')),
                ('due_date_end', models.DateField(verbose_name='Дата окончания исполнения')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ADS.address', verbose_name='Адрес')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ADS.executor', verbose_name='Исполнитель')),
                ('specialist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ADS.specialist', verbose_name='Специалист')),
            ],
        ),
    ]
