# Generated by Django 4.2.7 on 2025-02-19 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ADS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatcherFullName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО диспетчера')),
            ],
        ),
        migrations.RemoveField(
            model_name='seti',
            name='avaria_choices',
        ),
        migrations.AddField(
            model_name='seti',
            name='heat_avaria_choices',
            field=models.CharField(choices=[('Boiler', 'Котельная'), ('CTP', 'ЦТП'), ('Chamber', 'Камера'), ('HeatLeak', 'Течь сети')], default='Boiler', max_length=20, verbose_name='Объект аварии тепла'),
        ),
        migrations.AddField(
            model_name='seti',
            name='improvement_avaria_choices',
            field=models.CharField(choices=[('DestroyedWell', 'Разрушен колодец'), ('Other', 'Иное')], default='DestroyedWell', max_length=20, verbose_name='Объект аварии'),
        ),
        migrations.AddField(
            model_name='seti',
            name='sewerage_avaria_choices',
            field=models.CharField(choices=[('SewerClog', 'Засор канализации'), ('SewerLeak', 'Течь сети'), ('WellLeak', 'Течь колодца'), ('Other', 'Иное')], default='SewerClog', max_length=20, verbose_name='Объект аварии канализации'),
        ),
        migrations.AddField(
            model_name='seti',
            name='water_avaria_choices',
            field=models.CharField(choices=[('WaterLeak', 'Течь сети'), ('Well', 'Колодец'), ('HydrantLeak', 'Течь пожарного гидранта'), ('Column', 'Колонка')], default='WaterLeak', max_length=20, verbose_name='Объект аварии воды'),
        ),
        migrations.AlterField(
            model_name='seti',
            name='applicant_type',
            field=models.CharField(choices=[('Citizen', 'Гражданин'), ('Government', 'Госорганы'), ('Organization', 'Организация')], default='Citizen', max_length=15, verbose_name='Тип заявителя'),
        ),
        migrations.AlterField(
            model_name='seti',
            name='category_choices',
            field=models.CharField(choices=[('Emergency', 'Аварийная'), ('Planned', 'Плановая'), ('Consultation', 'Консультация')], default='Emergency', max_length=12, verbose_name='Категория заявки'),
        ),
        migrations.AlterField(
            model_name='seti',
            name='resource_choices',
            field=models.CharField(choices=[('Heat', 'Тепло'), ('WaterSupply', 'Водоснабжение'), ('Sewerage', 'Канализация'), ('Improvement', 'Благоустройство')], default='Heat', max_length=15, verbose_name='Ресурс'),
        ),
        migrations.AlterField(
            model_name='seti',
            name='status',
            field=models.CharField(choices=[('New', 'Новая'), ('Transferred', 'Передано на исполнение'), ('InProgress', 'В работе'), ('Completed', 'Завершена')], default='New', max_length=15, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='seti',
            name='type_choices',
            field=models.CharField(choices=[('Primary', 'Первичная'), ('Repeated', 'Повторная')], default='Primary', max_length=10, verbose_name='Тип обращения'),
        ),
        migrations.AddField(
            model_name='seti',
            name='dispatcher_full_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ADS.dispatcherfullname', verbose_name='ФИО диспетчера'),
        ),
    ]
