# Generated by Django 5.1.3 on 2025-04-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wear_access',
            field=models.BooleanField(default=False, verbose_name="Доступ к 'Расчёт износа здания'"),
        ),
    ]
